
org: luizestudo

service: AsyncReport

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  world:
    handler: src/functions/world.handler
    events:
      - httpApi:
          path: /world
          method: get
